version: "2"

services:
  namenode:
    image: namenode:0.1.1
    container_name: namenode
    volumes:
      - /hadoop/dfs/name:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020
  
  resourcemanager:
    image: resourcemanager:0.1.1
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088

  historyserver:
    image: historyserver:0.1.1
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - /hadoop/yarn/timeline:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188

  nodemanager1:
    image: nodemanager:0.1.1
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - 8042:8042

  datanode1:
    image: datanode:0.1.1
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: datanode:0.1.1
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode3:
    image: datanode:0.1.1
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env