version: "2"

services:
  namenode:
    image: namenode:0.1.1
    container_name: namenode
    volumes:
      - /hadoop/dfs/name:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 8020:8020
  
  resourcemanager:
    image: resourcemanager:0.1.1
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - 8088:8088

  historyserver:
    image: historyserver:0.1.1
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - /hadoop/yarn/timeline:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - 8188:8188

  datanode1:
    image: datamanager:0.1.1
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode2:
    image: datamanager:0.1.1
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
  
  datanode3:
    image: datamanager:0.1.1
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode4:
    image: datamanager:0.1.1
    container_name: datanode4
    depends_on:
      - namenode
    volumes:
      - /hadoop/dfs/data4:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  zoo:
    image: zookeeper
    container_name: zoo
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - /zookeeper/datalog:/datalog
      - /zookeeper/data:/data
    ports:
      - 2181:2181

  hbase-master:
    image: hbase-master:0.1.1
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 zoo:2181"
    ports:
      - 16010:16010
      - 60080:60080

  hbase-region:
    image: hbase-region:0.1.1
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hbase.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:9870 zoo:2181 hbase-master:16010"
