version: "2"

services:
  namenode:
    image: namenode:0.1.2
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet
    ports:
      - 9870:9870
      - 8020:8020
  
  resourcemanager:
    image: resourcemanager:0.1.2
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet
    ports:
      - 8088:8088

  historyserver:
    image: historyserver:0.1.2
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    volumes:
      - historyserver:/mr-history
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet
    ports:
      - 19888:19888
      - 10020:10020

  datanode1:
    image: datamanager:0.1.2
    container_name: datanode1
    depends_on:
      - namenode
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet

  datanode2:
    image: datamanager:0.1.2
    container_name: datanode2
    depends_on:
      - namenode
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet

  datanode3:
    image: datamanager:0.1.2
    container_name: datanode3
    depends_on:
      - namenode
    volumes:
      - datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - hadoopnet

  sparksubmit:
    image: spark:0.1.2
    container_name: sparksubmit
    depends_on:
      - namenode
      - resourcemanager
    env_file:
      - ./hadoop.env
      - ./spark.env
    networks:
      - hadoopnet
    ports:
      - 18080:18080

  zoohbase:
    image: zookeeper
    container_name: zoohbase
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - zoohbasedatalog:/datalog
      - zoohbasedata:/data
    networks:
      - hadoopnet
    ports:
      - 2181:2181

  hbase-master:
    image: hbase-master:0.1.2
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hbase.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870 zoohbase:2181"
    networks:
      - hadoopnet
    ports:
      - 16010:16010
      - 60080:60080

  hbase-region:
    image: hbase-region:0.1.2
    container_name: hbase-region
    hostname: hbase-region
    env_file:
      - ./hbase.env
    networks:
      - hadoopnet
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:9870 zoohbase:2181 hbase-master:16010"

volumes:
  datanode1:
  datanode2:
  datanode3:
  namenode:
  historyserver:
  zoohbasedatalog:
  zoohbasedata:

networks:
  hadoopnet:

