export HADOOP_PATH=/hadoop
mkdir $HADOOP_PATH
mkdir $HADOOP_PATH/yarn
mkdir $HADOOP_PATH/dfs
mkdir $HADOOP_PATH/yarn/timeline
mkdir $HADOOP_PATH/dfs/name
mkdir $HADOOP_PATH/dfs/data1
mkdir $HADOOP_PATH/dfs/data2
mkdir $HADOOP_PATH/dfs/data3
